stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: amazingcms/mdx-renderer:${CICD_GIT_TAG}
      pushRemote: true
      registry: harbor.amazingdesign.eu
timeout: 60
notification: {}
